name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'gradle'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Set up cache for SAP artifacts
      uses: actions/cache@v2
      with:
        key: sap-artifacts-cache-${{ hashFiles('manifest.json') }}
        path: dependencies
    - name: SAP download config
      env:
        USER_CONFIG: ${{ secrets.GRADLE_USER_CONFIG }}
        AUTHORIZATION: ${{ secrets.SAP_DOWNLOAD_AUTHORIZATION }}
      shell: bash
      run: |
        mkdir -p ${HOME}/.gradle
        echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
        echo "${USER_CONFIG}" >> ${HOME}/.gradle/gradle.properties
        echo "sUserAuthorization=${AUTHORIZATION}" >> ${HOME}/.gradle/gradle.properties
    - name: Bootstrap platform
      run: ./gradlew setupLocalDevelopment
    - name: Adapt configuration for CI
      run: |
        echo "HYBRIS_OPT_CONFIG_DIR=$GITHUB_WORKSPACE/hybris/config/local-config" >> $GITHUB_ENV
        cat $GITHUB_WORKSPACE/ci/local-testing.properties >> $GITHUB_WORKSPACE/hybris/config/local-config/99-local.properties
    - name: Build platform
      run: ./gradlew yall
    - name: Run unit tests
      run: |
        ./gradlew yunittests
        
        # Target never fails, therefore, check for test errors and fail if errors were found
        for file in $GITHUB_WORKSPACE/hybris/log/junit/test-results/*.xml; do if [ "$(grep -cE '<(error|failure)' "${file}")" -gt 0 ]; then exit 1; fi; done
    - name: Coverage Report
      env:
        TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        # Generate codecov report 
        java -jar $GITHUB_WORKSPACE/ci/jacococli.jar report $GITHUB_WORKSPACE/hybris/log/junit/jacoco.exec --classfiles $GITHUB_WORKSPACE/hybris/bin/custom --sourcefiles $GITHUB_WORKSPACE/hybris/bin/custom --xml $GITHUB_WORKSPACE/hybris/log/junit/jacoco.xml

        # Download codecov uploader
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        
        # Upload report to codecov
        if [ $GITHUB_REF_TYPE -eq "branch" ]; then
          ./codecov -f $GITHUB_WORKSPACE/hybris/log/junit/jacoco.xml -Z --build $GITHUB_RUN_ID --branch GITHUB_REF_NAME -t $TOKEN
        else
          ./codecov -f $GITHUB_WORKSPACE/hybris/log/junit/jacoco.xml -Z --build $GITHUB_RUN_ID --tag GITHUB_REF_NAME -t $TOKEN
        fi