name: Code Analysis

on:
  push:
    branches: [develop, "feature/**"]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: "17"
          cache: "gradle"
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Verify code conventions
        run: ./gradlew spotlessCheck
