name: Code Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-analysis: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'gradle'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Verify code conventions
      run: ./gradlew spotlessCheck
    - name: Verify PMD ruleset
      id: pmd
      uses: pmd/pmd-github-action@6d98898be0d59f46ec37dafcea33d8f8f55acfd1
      with:
        rulesets: 'conventions/pmd-java-quickstart.xml'
        sourcePath: 'hybris/bin/custom/sapcxtools'
