name: Dependency Check

on:
  push:
    branches: [develop]
    paths:
      - "core-customize/hybris/bin/custom/sapcxtools/**/*.java"
      - "core-customize/hybris/bin/custom/sapcxtools/**/*-beans.xml"
      - "core-customize/hybris/bin/custom/sapcxtools/**/*-items.xml"
      - "core-customize/hybris/bin/custom/sapcxtools/**/extensioninfo.xml"
      - "core-customize/hybris/bin/custom/sapcxtools/**/external-dependencies.xml"
  pull_request:
    branches: [main, develop]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extension: ["sapcommercetoolkit", "sapcxbackoffice", "sapcxreporting", "sapcxsearch", "sapcxsinglesignon"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "17"
          cache: "gradle"
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up cache for SAP artifacts
        uses: actions/cache@v2
        with:
          key: sap-artifacts-cache-${{ hashFiles('core-customize/manifest.json') }}
          path: dependencies
      - name: SAP download config
        env:
          SAPCX_ARTEFACT_USER: ${{ secrets.SAPCX_ARTEFACT_USER }}
          SAPCX_ARTEFACT_PASSWORD: ${{ secrets.SAPCX_ARTEFACT_PASSWORD }}
        shell: bash
        run: |
          mkdir -p ${HOME}/.gradle
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "SAPCX_ARTEFACT_USER=${SAPCX_ARTEFACT_USER}" >> ${HOME}/.gradle/gradle.properties
          echo "SAPCX_ARTEFACT_PASSWORD=${SAPCX_ARTEFACT_PASSWORD}" >> ${HOME}/.gradle/gradle.properties
      - name: SAP Commerce environment
        run: |
          echo "HYBRIS_OPT_CONFIG_DIR=$GITHUB_WORKSPACE/core-customize/hybris/config/local-config" >> $GITHUB_ENV
          echo "HYBRIS_BIN_DIR=$GITHUB_WORKSPACE/core-customize/hybris/bin" >> $GITHUB_ENV
          echo "HYBRIS_CONF_DIR=$GITHUB_WORKSPACE/core-customize/hybris/config" >> $GITHUB_ENV
          echo "HYBRIS_LOG_DIR=$GITHUB_WORKSPACE/core-customize/hybris/log" >> $GITHUB_ENV
      - name: Configure extension
        run: |
          cp -f ci/config/localextensions-template.xml $HYBRIS_CONF_DIR/localextensions.xml
          sed -i 's/EXTENSIONNAME/${{ matrix.extension }}/' $HYBRIS_CONF_DIR/localextensions.xml
      - name: Bootstrap platform
        run: ./gradlew setupLocalDevelopment
      - name: Build platform
        run: ./gradlew yall
