name: PMD Code Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pmd-code-scan:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run PMD
        id: pmd
        uses: pmd/pmd-github-action@6d98898be0d59f46ec37dafcea33d8f8f55acfd1
        with:
          rulesets: 'conventions/pmd-java-quickstart.xml'
          sourcePath: 'hybris/bin/custom/sapcxtools'
